### ISSUE TITLE
Source customization like CASK?

### ISSUE THREAD

**Issue by liuyinz** [conao3/keg.el#42]
With Cask file , we can customize source with mirror temporarily, 
e.g.
```elisp
(source "gnu"   "http://elpa.zilongshanren.com/gnu/")
(source "melpa" "http://elpa.zilongshanren.com/melpa/")
```
While in Keg file, it seems not allowed. I only can change the alist in `keg.el` itself. 
Can we fix that ?

**Comment by conao3** [comment]
@ROCKTAKEY, we can support it?

**Comment by ROCKTAKEY** [comment]
I will try it.

**Comment by ROCKTAKEY** [comment]
@liuyinz, now you can write like this:
```emacs-lisp
(source (gnu . "http://elpa.zilongshanren.com/gnu/")
        (melpa . "http://elpa.zilongshanren.com/melpa/"))
```

**Comment by liuyinz** [comment]
Succeed! Thanks! @ROCKTAKEY

**Comment by liuyinz** [comment]
@ROCKTAKEY  It seems when using `keg lint`, keg still auto-install `package-lint` form elpa.gnu.org... I guess not fixed completely.

**Comment by conao3** [comment]
This is design issue, I believe. `keg` depends on the source code, which is assumed from where it is supposed to be.
Being able to fetch a user's package dependencies from wherever they want is useful, but is there any benefit to being able to fetch keg dependencies from wherever they want...?

**Comment by conao3** [comment]
anyway, reopen this issue.

**Comment by liuyinz** [comment]
But one of reasons somebody using mirror maybe just cann't connect to melpa or gnu...
Anyway, is there any plan to supprot to install dependency from github directly?

**Comment by ROCKTAKEY** [comment]
Maybe, some users cannot fetch from gnu or melpa archive due to firewall. I will add environmenral variable to set package-archives.

**Comment by conao3** [comment]
Thanks both. I finally found that users needed this feature.
Just for reference, is it possible to support this feature in keg, like a proxy, to make all communication to melpa.org access the mirror?

**Comment by liuyinz** [comment]
@ROCKTAKEY env would be the best choice.

**Comment by liuyinz** [comment]
And I find another bug:
when I use `keg install` or `keg lint`, `importing package-keyring.gpg` always make a directroy : `elpa/gnupg` in my `user-emacs-directory` root dir. Whether it's a bug or designed? I think put that into `.keg/28.0.60/elpa` with other dependency together would be better rather than polluting user config dir. I don't use package.el in my personal configuration actually.

**Comment by ROCKTAKEY** [comment]
It is also bug. I will fix it, too.

**Comment by ROCKTAKEY** [comment]
@liuyinz  Environmental variable `KEGPACKAGEARCHIVES` is now available.
```shell
KEGPACKAGEARCHIVES="((gnu . \"http://elpa.zilongshanren.com/gnu/\") (melpa . \"http://elpa.zilongshanren.com/melpa/\"))" keg 
```

Env is more recommended than source customization in Keg file, when you want to change URL to mirror one. Source customization is recommended when you want to add another source.

**Comment by ROCKTAKEY** [comment]
Gnupg file bug might be fixed. Is it work correctly, @liuyinz?

**Comment by liuyinz** [comment]
@ROCKTAKEY All fixed, Thanks!

**Comment by liuyinz** [comment]
https://github.com/conao3/keg.el#packagerecipe
When you update readme.md, don't forget to revise this typo:
> package-args could accept alist and currently only recipe is **~~varid~~**.
